dist: trusty
sudo: false

language: scala

jdk:
  - openjdk11

scala:
  - 2.12.10
#  - 2.13.0

script: sbt --warn ++$TRAVIS_SCALA_VERSION clean coverage test

after_success: sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "STylCrPbSP/R8gAkQ3K+RsSAqGNX3sUeqfF+vIfA5IrQWE44f7yJKVhZ9Dr/TPo+UkNKU9AtB5iCLa2BUpSPuHjexZkfZnjBHO/knv5VociHNq6x+w0FmSDnKnvpbphsAfCiMqEvZ7Dlrccj9xn17DLjIWbMNPOgop3fr9FCWTVvAetxgZ2RaGyhezT4d5CeNc/e3pnNy0Cq/S8TgBPbVsQvDYh7SHdfOPZRZHSQd/Z1cw6e2+EgKdApsTJMm7tqkRvpRehf1nJugWsyRKBfGZPmvygm3V951jcBZ6tsDWfXUaMC/we/0yKdDIRnto8in6fECDz53arMRBgxgNWnllChKBBG7ewW9dxfsqsKNz1ZUgpsRVbSzDbBnebiSA+0nuuWlBNXt52gWxThPBrXtUUNv3ONSjfstLaeHTBPdTO4mBn67ZnhiQ40VhLn906vSl727xyr2qdgueyd+fxbkQZPVehTO9tLl6RvRcjhLi96T08OPzuhPQPrqbAAmHzOJdNxaX2XQNTblBFjaAvU5b8PFkDZOsD+Bj0yFI5bLeG1vL+l8j0dFu8KVF8Xw3oEGrHl1VZFRbhkeyuMtOjTXfnBRkB5cv4NE27VacbNgBDqz6vAP4i9DVy/1DTIQ0T/qn/7hwEOXMa9UMYnbNhOLT+p1KaFUhmxmR9wITdm+xo="

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

addons:
  sonarcloud:
    organization: "evolution-gaming"
    token:
      secure: "jMopO89iXGGz+BDg5bJFQCbHO5kLLPsAAJfAY6YNS12CRqbewbd2fZVBHzmWEo4dtI50AgGWuDmRrjT84Lh2+9N5R6/qia5Kx8YqBqApwFpDvmXILhBE5fF9hK8Odc+uwDoXjNpF7d5kMkRyzIRMSns+XdLkDomzMP0g7wz9CUqfRRrjW6gqbiMLg3kn3FRYAWA6EJbZSwZ57XKrhg8YpG/Nejlbs2wMk1RL0oKDMPTxMujkIwHv6mOvGdB6wm33INYA4tp4dkvmC8jFo/LwLD+c3NEwPpvUTAUPI2VzEpjrg71gMMfhUoMJvyOywL6NmhnNXCXeYgArGVOmAj1puRP2PI4SOeHmObet1k33lZ39po2DxnrWiwRGCyjfAKq2vjBxcuEjocdWXWFn39l1xVyewJ1frIxuI7njSkKOJ+pqWjjvq+LFI/PJfOpJtcZr3+2Fm5QXENC+Y4Oyepnf7f4xdHMOuStsBdtyItArt1YrghfEXmboe5+2A/YeWxf/9KMWJnAPTYBhCv4Gs8bpx7a2dxsrPh7Z30MpCYJrl+9TzctsZfC3PJzBvwY0GDXr8uqwZ01bu3PVzdrGBPfA8gMRKdNgmIAxqkgI1+nvKtkxA8uuUADxhaVFnmGiGI1psZKxIk2E44Zw7ixKtreORI6/k+/wbtoxLop4mNxdrdc="